### ISSUE TITLE
Add end-to-end tests for UI

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#194]
See https://reactjs.org/docs/testing.html

@NJaku01 Please make a short plan for the tests, like, which components can you test small scale and what should be [end-to-end](https://reactjs.org/docs/testing-environments.html#end-to-end-tests-aka-e2e-tests) tests (Puppeteer looks nice).

- [x] core components are tested
- [x] create ERC and "look at it" (end-to-end)
- [x] all tabs are tested (inspect, check, ...)
- [x] run analysis (look at comparison, look logs)
- [x] manipulate ERC (create binding, manipuate)
- [x] tests run as a GitHub action
- [x] save images during GitHub action run

**Comment by nuest** [comment]
This will require an instance of the o2r API to run - let's try to use the demo server first before we try to run the API for real (or implement a mock-version of the API, which might be a lot easier if we stick to "reading" interaction).

**Comment by nuest** [comment]
See the tests of o2r-muncher for helper functions and examples how to quickly upload publish test compendia, and also simple test workspaces. If you have problems with the publication process via the UI, the "reading" of an ERC could be solved that way.

- https://github.com/o2r-project/o2r-muncher/blob/master/test/util.js (helper functions for direct upload - BUT these also require you to insert the required users directly to the databaset etc. - so get in touch with me again before you go down this road)
- https://github.com/o2r-project/o2r-muncher/tree/master/test/workspace/dummy (dummy workspace - runs very quickly, but you have to enter all metadata through the UI)
- **https://github.com/o2r-project/o2r-muncher/tree/master/test/workspace/rmd-data** (workspace that should be have all metadata and be directly "publishable")

Re. docker-compose in GitHub action:

- https://gist.github.com/cecilemuller/437d7340b9f095cf5635dc9780a05092
- https://gist.github.com/ashiklom/9a25fbf6d9639bb13da3c05d1f003633
- https://github.community/t/how-to-use-docker-compose-with-github-actions/16850

### Tasks

1. GH action step to API and UI
2. GH action step to run jest tests

**Comment by NJaku01** [comment]
GH action cannot start the web server regularly. Inspect: https://github.com/NJaku01/o2r-UI/runs/1707454998

Possible workarounds:

- Inspect `docker logs ui_webserver`
- Use GH actions locally: https://github.com/nektos/act
- Instead of building the microservices, use the api from the demo server https://o2r.uni-muenster.de/api

**Comment by nuest** [comment]
@NJaku01 Can you please note here which of the workarounds you eventually used? Thanks!

**Comment by NJaku01** [comment]
Following workarounds worked:
Inspect different logs. with docker logs ui_container_1
Debug Github actions: https://github.com/marketplace/actions/debugging-with-tmate
